### ISSUE TITLE
LaneDirection estimation in RssObjectPositionExtractor::newLaneSegment

### ISSUE THREAD

**Issue by xiaong** [intel/ad-rss-lib#106]
One question for positive lane or negative lane estimation logic:
In RssObjectPositionExtractor::newLaneSegment the object lane direction is gotten from laneSegment laneDrivingDirection.  But if the object is occupying both positive and negtive lane, the lane type will be overwritten by the last occupied laneSegment. Will there be a logic bug？
```
if (laneSegment.drivingDirection == LaneDrivingDirection::Positive)
      {
        mObjectDimensions.onPositiveLane = true;
      }

      if (laneSegment.drivingDirection == LaneDrivingDirection::Negative)
      {
        mObjectDimensions.onNegativeLane = true;
      }
```
THX!

**Comment by berndgassmann** [comment]
Hi,
this function is collecting both information, because it's collecting onPositiveLane as well as onNegativeLane flag. At this place nothing is overwritten. In case the vehicle is touching both kind of lanes, both flags are true.

That information is later used to determine if the the vehicle is in respect to the current situation actually on the correct lane or not by filling the isInCorrectLane flag for [Non-Intersection-Cases](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/impl/src/core/RssSituationExtraction.cpp#L168) and for [Intersection cases](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/impl/src/core/RssSituationExtraction.cpp#L217).
In general isInCorrectLane flag is only relevant in the opposite use-case to distinguish between [BrakeMin and BrakeMinCorrect](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/impl/src/situation/RssStructuredSceneNonIntersectionChecker.cpp#L212) expected braking deceleration.

I hope this answers your question and clears your doubts.

**Comment by xiaong** [comment]
Got it. Thank you for your answer!
