### ISSUE TITLE
Question: Init object by metric coordinates in map_integration

### ISSUE THREAD

**Issue by max-zipfl-fzi** [intel/ad-rss-lib#125]
Hello,
I am trying to understand the python example of map_integration. There, the objects are initialized with geodetic coordinates (ENU). Is it possible to define objects with x and y?
How would an example look like?

`

        # example from interface_test.py
        positionGeo = ad.map.point.createGeoPoint(lon, lat, ad.map.point.Altitude(0.)) # -> I want to exchange lon and lat by x and y
        # fill the result position
        resultObject.enuPosition.centerPoint = ad.map.point.toENU(positionGeo)
        resultObject.enuPosition.heading = ad.map.point.createENUHeading(yawAngle)
        resultObject.enuPosition.dimension.length = ad.physics.Distance(4.5)
        resultObject.enuPosition.dimension.width = ad.physics.Distance(2.)
        resultObject.enuPosition.dimension.height = ad.physics.Distance(1.5)
        resultObject.enuPosition.enuReferencePoint = ad.map.access.getENUReferencePoint()
`

If this is not possible, is there an option to read the projection string from an opendrive file using this library with python. I have already found the mapdata reference, but haven't found a useful way to retrieve it - without rebuilding the whole factorypipeline.

Thanks!

**Comment by berndgassmann** [comment]
Hi,
ad.map.point provides different transformations between coordinate frames. There are different overloads of (to/fromGeo, to/fromENU, to/fromECEF). See [map-doc](https://ad-map-access.readthedocs.io/en/latest/ad_map_access/apidoc/html/namespacead_1_1map_1_1point.html).
Indeed the geo coordinates are here even not the actual input format since it is transformed by toENU.
So you can just skip the Geo coordinates and immediately enter
```
resultObject.enuPosition.centerPoint.x = ad.map.point.ENUCoordinate(your-x-value)
resultObject.enuPosition.centerPoint.y = ad.map.point.ENUCoordinate(your-y-value)
resultObject.enuPosition.centerPoint.z = ad.map.point.ENUCoordinate(your-z-value)
```

For some more details on the used coordinate systems look [here](https://ad-map-access.readthedocs.io/en/latest/ad_map_access/HLD_MapDataModel/#coordinate-systems).

If you load an open drive map file, the projection string is internally already considered when doing the coordinate system transformations.

Hope this helps.
Bernd.

**Comment by max-zipfl-fzi** [comment]
sorry for the late reply - thank you for the detailed explanation, it helped a lot.

Best
Max
