### ISSUE TITLE
Build instructions that don't use colcon? 

### ISSUE THREAD

**Issue by mrwesleycrusher** [intel/ad-rss-lib#71]
Hello,
Not to be too needy, but I am trying to build this library on arch, and I am having issues getting colcon to run. Based on the build instructions, the reason colcon is used is because the underlying carla ad_map_access library uses colcon. I tried building that on Ubuntu, but I was having issues getting that to build as well because of some issues with gtest. Would it be possible to get friendlier build instructions that use a more common tool like make/cmake/ninja? 

I am not super familiar with colcon so trying to troubleshoot the build has been rough.

Also, as an aside, why did intel license this library in a way that conflicts with CARLA's license? Just curious.

**Comment by berndgassmann** [comment]
Hi,
Actually cmake is used for building the stuff. Colcon is more or less calling cmake in all dependencies, and provides their installation paths towards the other projects so that they find the respective dependencies. The colcon.meta file lists some additional cmake parameters that are used when compiling with pure cmake. Therefore, cmake is totally fine, it just needs a bunch of successive calls (within dependencies/spdlog, with dependencies/map and then within ad-rss-lib).
And in respect to the license: it stresses the research character of this implementation which is not suitable for commercial or production release (see also https://github.com/intel/ad-rss-lib/blob/master/RELEASE_NOTES_AND_DISCLAIMERS.md).
