### ISSUE TITLE
Question on object detection by RSS sensor in Carla 

### ISSUE THREAD

**Issue by yashwantj** [intel/ad-rss-lib#89]
Dear,

In Carla, we have observed that, even an occluded vehicle/actor is detected by rss sensor. But in real world scenarios that is not possible. Is there any way to differentiate target detection for,

1. Occluded
2. Out of FOV etc..

For example, in below picture, sensor detected two vehicles. Out of two, one is occluded (car covered by another car). 
![Capture](https://user-images.githubusercontent.com/68522811/96665308-92dadc80-138f-11eb-89b4-a79131eeecb8.PNG)

For occlusion, is there any flag available? How we can filter out occluded vehicle in RSS sensor?

Regards,
Yashwant

**Comment by berndgassmann** [comment]
Ok, thanks for clarification.

We introduced the RssSensor.register_actor_constellation_callback() function to configure the parameters for every other vehicle/object individually
https://carla.readthedocs.io/en/latest/python_api/#carlarsssensor

Like this, one is able to set those that should not be considered to
actor_constellation_result.rss_calculation_mode = ad.rss.map.RssMode.NotRelevant
see e.g. https://github.com/carla-simulator/carla/blob/dev/PythonAPI/examples/rss/rss_sensor.py#L128
That would be the cleanest way to ignore those.

Be aware: Per RSS rules one should be cautious in occluded areas. To get the system working correctly just ignoring the vehicles is not sufficient. As you mentioned, the FOV has to be considered, to get an idea where occluded objects might be, and by some means these have to taken into account. The ad_rss lib per se supports Artificial Objects, so that might be a way to come to a full support for occlusions within CARLA implementation in future to place reasonable artificial objects at occluded areas to get them considered. This work item is on our roadmap, but we did not yet start on it.

Hope this helps,

Bernd.
