### ISSUE TITLE
Question on calculateTimeForDistance

### ISSUE THREAD

**Issue by Freiheit1992** [intel/ad-rss-lib#95]
Hello, in function calculateTimeForDistance, there's a judgement on whether the car's acceleration is zero or not:
>   if ((acceleration == Acceleration(0.)) || (currentSpeed >= maxSpeedOnAcceleration))

> 
However, even if current speed is higher than max_speed, the acc can still be minus, so, I think here it should be: 
> if ((acceleration == Acceleration(0.)) || (currentSpeed >= maxSpeedOnAcceleration && acceleration > 0))

> 
Am I wrong?

**Comment by berndgassmann** [comment]
Hi,
Thanks for raising this issue.

In general the "feature" of maxSpeedOnAcceleration should only limit the actual acceleration. So yes, your statement is totally correct. The suggested changes will enforce this.

I would even go a step further and state that, theoretically, the configuration with currentSpeed >= maxSpeedOnAcceleration && acceleration<0 should never be called (that's most probably why this was not considered by the code). But when looking into calculateTimeToCoverDistance where calculateTimeForDistance is called, I see this: 
result = calculateTimeForDistance(
            speedAfterResponseTime, maxSpeedOnAcceleration, aAfterResponseTime, remainingDistance, requiredTime);
where the the described configuration actually can happen!
So this line of code should also change to:
result = calculateTimeForDistance(
            speedAfterResponseTime, std::numeric_limits<Speed>::max(), aAfterResponseTime, remainingDistance, requiredTime);
because it considers the deceleration AFTER the response time where it doesn't matter what maxSpeedOnAcceleation value is provided.

So without having tested it, I'd say you are totally right and would rate this a bug to be fixed.

**Comment by Freiheit1992** [comment]
Hi, thank you for your reply,

I notice that calculateTimeForDistance is called twice in calculateTimeToCoverDistance. For the 2nd calculateTimeForDistance, yes, it's in deceleration phase; but for the first one: 

> result = calculateTimeForDistance(
>         currentSpeed, maxSpeedOnAcceleration, aUntilResponseTime, distanceToCover, requiredTime);

maybe currentSpeed >= maxSpeedOnAcceleration && acceleration<0 is still possible?

**Comment by berndgassmann** [comment]
Hi,
no the first one cannot become negative, because it's the acceleration within the response time which is >=0. While response time the worst expected case is considered, where the accel_max parameter is an upper border of it. And in the calculations only that border is of relevance.
But for sure, I'll adapt both lines of code when fixing.
